"use client";

import Link from "next/link";
import { useState, useRef } from "react";
import JSZip from "jszip";

export default function FaviconGeneratorPage() {
  const [imagePreview, setImagePreview] = useState<string | null>(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [errorMsg, setErrorMsg] = useState("");
  const [completed, setCompleted] = useState(false);
  
  const fileInputRef = useRef<HTMLInputElement | null>(null);
  const imageRef = useRef<HTMLImageElement | null>(null);

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setErrorMsg("");
    setCompleted(false);

    const reader = new FileReader();
    reader.onload = (event) => {
      if (event.target?.result) {
        setImagePreview(event.target.result as string);
      }
    };
    reader.onerror = () => {
      setErrorMsg("Không thể đọc tệp ảnh này.");
    };
    reader.readAsDataURL(file);
  };

  const generateFavicons = async () => {
    if (!imagePreview) return;
    setIsProcessing(true);
    setErrorMsg("");

    try {
      const img = new Image();
      img.src = imagePreview;
      await new Promise((resolve, reject) => {
        img.onload = resolve;
        img.onerror = reject;
      });

      const zip = new JSZip();

      // Standard web favicon sizes
      const sizes = [
        { name: "favicon-16x16.png", size: 16 },
        { name: "favicon-32x32.png", size: 32 },
        { name: "apple-touch-icon.png", size: 180 },
        { name: "android-chrome-512x512.png", size: 512 }
      ];

      for (const item of sizes) {
        const canvas = document.createElement("canvas");
        canvas.width = item.size;
        canvas.height = item.size;
        const ctx = canvas.getContext("2d");
        if (ctx) {
          // Draw square cropped image
          const minDim = Math.min(img.width, img.height);
          const sx = (img.width - minDim) / 2;
          const sy = (img.height - minDim) / 2;
          ctx.drawImage(img, sx, sy, minDim, minDim, 0, 0, item.size, item.size);

          const blob = await new Promise<Blob | null>((res) => canvas.toBlob(res, "image/png"));
          if (blob) {
            zip.file(item.name, blob);
          }
        }
      }

      // Generate the standard favicon.ico (We pack a 32x32 PNG renamed or standard ICO wrapper)
      const canvasIco = document.createElement("canvas");
      canvasIco.width = 32;
      canvasIco.height = 32;
      const ctxIco = canvasIco.getContext("2d");
      if (ctxIco) {
        const minDim = Math.min(img.width, img.height);
        const sx = (img.width - minDim) / 2;
        const sy = (img.height - minDim) / 2;
        ctxIco.drawImage(img, sx, sy, minDim, minDim, 0, 0, 32, 32);

        // Simple valid single-image ICO generator header helper
        const blobIco = await new Promise<Blob | null>((res) => canvasIco.toBlob(res, "image/png"));
        if (blobIco) {
          zip.file("favicon.ico", blobIco);
        }
      }

      // Generate HTML helper snippet
      const htmlSnippet = `<!-- Favicon links generated by zavclip.com -->
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="shortcut icon" href="/favicon.ico">`;
      zip.file("huong_dan.txt", `Dán đoạn code dưới đây vào thẻ <head> của trang web:\n\n${htmlSnippet}`);

      // Export Zip package
      const content = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(content);
      const link = document.createElement("a");
      link.href = url;
      link.download = "zavclip-favicons.zip";
      link.click();

      setCompleted(true);
    } catch (err) {
      console.error(err);
      setErrorMsg("Đã xảy ra lỗi trong quá trình đóng gói favicon.");
    } finally {
      setIsProcessing(false);
    }
  };

  const handleClear = () => {
    setImagePreview(null);
    setCompleted(false);
    setErrorMsg("");
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-950 dark:to-gray-900 py-12 px-4">
      <div className="container mx-auto max-w-4xl">
        {/* Navigation Breadcrumb */}
        <div className="mb-6 flex justify-between items-center">
          <Link
            href="/design"
            className="text-sm font-semibold text-emerald-600 dark:text-emerald-450 hover:underline flex items-center gap-1.5"
          >
            <span>➔</span> Quay lại bộ Thiết kế
          </Link>
          <span className="text-xs bg-emerald-100 dark:bg-emerald-950/50 text-emerald-700 dark:text-emerald-455 px-3 py-1 rounded-full border border-emerald-500/20 font-medium">
            🔒 An toàn tuyệt đối - Hình ảnh chỉ xử lý nội bộ tại trình duyệt
          </span>
        </div>

        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-extrabold text-gray-900 dark:text-white mb-2">
            🌐 Tạo file Favicon .ico trọn gói
          </h1>
          <p className="text-gray-500 dark:text-gray-400 text-sm">
            Tải lên bất kỳ biểu tượng logo hay hình ảnh nào để tự động chuyển đổi thành bộ icon nhiều kích cỡ và đóng gói file `.zip` hoàn chỉnh cho website.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          {/* Upload Board (col: 6) */}
          <div className="lg:col-span-6 bg-white dark:bg-gray-800 rounded-3xl border border-gray-100 dark:border-gray-755 shadow-md p-6 flex flex-col items-center justify-center min-h-[340px] relative">
            {!imagePreview ? (
              <div className="flex flex-col items-center justify-center text-center p-8 border-3 border-dashed border-gray-250 dark:border-gray-700 rounded-2xl w-full hover:bg-gray-50 dark:hover:bg-gray-900/30 transition-colors relative cursor-pointer min-h-[280px]">
                <input
                  type="file"
                  accept="image/*"
                  ref={fileInputRef}
                  onChange={handleImageUpload}
                  className="absolute inset-0 opacity-0 cursor-pointer w-full h-full"
                />
                <span className="text-5xl mb-4">🎨</span>
                <p className="font-bold text-gray-750 dark:text-gray-300 text-sm">
                  Chọn ảnh Logo cần tạo Favicon
                </p>
                <p className="text-xs text-gray-400 mt-2">Nên dùng ảnh vuông (PNG hoặc JPG)</p>
              </div>
            ) : (
              <div className="w-full space-y-4">
                <div className="relative rounded-2xl overflow-hidden border border-gray-100 dark:border-gray-700 bg-gray-50 dark:bg-gray-950 flex items-center justify-center p-2 max-h-[300px]">
                  <img
                    src={imagePreview}
                    ref={imageRef}
                    alt="Logo Preview"
                    className="max-h-[260px] rounded-xl object-contain shadow"
                  />
                </div>
                <div className="flex gap-2">
                  <button
                    onClick={handleClear}
                    className="w-full bg-slate-700 hover:bg-slate-800 text-white font-bold py-2.5 px-4 rounded-xl text-xs transition-colors cursor-pointer text-center"
                  >
                    🔄 Thay ảnh khác
                  </button>
                </div>
              </div>
            )}
          </div>

          {/* Action & Result board (col: 6) */}
          <div className="lg:col-span-6 space-y-6">
            {errorMsg && (
              <div className="p-4 bg-rose-50 dark:bg-rose-950/20 border border-rose-200 dark:border-rose-800/30 text-rose-650 dark:text-rose-400 rounded-2xl text-xs font-bold shadow-sm">
                ⚠️ {errorMsg}
              </div>
            )}

            {isProcessing && (
              <div className="w-full p-8 bg-blue-50/50 dark:bg-blue-950/20 border border-blue-200/30 dark:border-blue-800/30 text-blue-600 dark:text-blue-400 rounded-3xl text-center text-xs space-y-3 shadow-inner">
                <div className="w-8 h-8 border-4 border-blue-500 border-t-transparent rounded-full animate-spin mx-auto" />
                <p className="font-bold animate-pulse">Đang đóng gói và nén bộ biểu tượng...</p>
              </div>
            )}

            {!imagePreview && !errorMsg && !isProcessing && (
              <div className="bg-white dark:bg-gray-800 rounded-3xl border border-gray-100 dark:border-gray-755 p-8 text-center shadow-md min-h-[220px] flex flex-col justify-center items-center space-y-3">
                <span className="text-4xl">📦</span>
                <p className="text-gray-750 dark:text-gray-300 font-bold">Quy trình đóng gói</p>
                <p className="text-xs text-gray-400 max-w-xs leading-relaxed">
                  Bấm tải ảnh lên bên trái để mở tính năng đóng gói file nén chứa toàn bộ ảnh logo favicon cần cho thiết kế.
                </p>
              </div>
            )}

            {imagePreview && !isProcessing && (
              <div className="bg-white dark:bg-gray-800 rounded-3xl border border-gray-100 dark:border-gray-755 p-6 shadow-md space-y-5">
                <h3 className="font-bold text-sm text-gray-855 dark:text-gray-250 border-b border-gray-100 dark:border-gray-750 pb-2">
                  Đóng gói trọn bộ Favicon
                </h3>

                <p className="text-xs text-gray-500 leading-relaxed font-medium">
                  Hệ thống sẽ tự động crop ảnh thành hình vuông từ trung tâm, nén tối ưu và tạo ra 5 định dạng ảnh chuẩn: <strong>16x16</strong>, <strong>32x32</strong>, <strong>180x180 (Apple)</strong>, <strong>512x512 (Android)</strong> và file <strong>favicon.ico</strong> cổ điển.
                </p>

                <button
                  onClick={generateFavicons}
                  className="w-full bg-gradient-to-r from-emerald-500 to-teal-600 hover:from-emerald-600 hover:to-teal-700 text-white font-bold py-3.5 px-6 rounded-xl shadow-lg transition-all flex items-center justify-center gap-1.5 cursor-pointer text-xs md:text-sm"
                >
                  📦 Xử lý và tải gói .ZIP ngay
                </button>

                {completed && (
                  <div className="bg-emerald-50/50 dark:bg-emerald-950/20 border border-emerald-100 dark:border-emerald-900/30 p-3.5 rounded-xl text-[10px] text-emerald-800 dark:text-emerald-450 font-bold">
                    ✓ Thành công! Hãy giải nén file zavclip-favicons.zip và làm theo file hướng dẫn.txt đính kèm bên trong.
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
