"use client";

import Link from "next/link";
import { useState, useEffect, useRef } from "react";
import JsBarcode from "jsbarcode";

type BarcodeFormat = "CODE128" | "EAN13" | "UPC" | "CODE39" | "ITF" | "MSI" | "pharmacode";

export default function BarcodeGeneratorPage() {
  const [format, setFormat] = useState<BarcodeFormat>("CODE128");
  const [value, setValue] = useState("123456789012");
  
  // Customization
  const [lineColor, setLineColor] = useState("#000000");
  const [bgColor, setBgColor] = useState("#ffffff");
  const [height, setHeight] = useState(100);
  const [width, setWidth] = useState(2);
  const [displayValue, setDisplayValue] = useState(true);

  const [errorMsg, setErrorMsg] = useState("");
  const svgRef = useRef<SVGSVGElement | null>(null);

  const generateBarcode = () => {
    setErrorMsg("");
    if (!svgRef.current) return;

    if (value.trim() === "") {
      setErrorMsg("Vui lòng nhập giá trị mã vạch.");
      return;
    }

    try {
      JsBarcode(svgRef.current, value, {
        format: format,
        lineColor: lineColor,
        background: bgColor,
        width: width,
        height: height,
        displayValue: displayValue,
        fontSize: 14,
        margin: 10,
        valid: (valid) => {
          if (!valid) {
            setErrorMsg(`Giá trị không hợp lệ với định dạng ${format}.`);
          }
        }
      });
    } catch (err: any) {
      console.error(err);
      setErrorMsg("Đã xảy ra lỗi khi tạo mã vạch. Vui lòng thử lại.");
    }
  };

  // Re-generate on changes
  useEffect(() => {
    generateBarcode();
  }, [format, value, lineColor, bgColor, height, width, displayValue]);

  // Set default placeholder based on format to avoid validation errors
  useEffect(() => {
    if (format === "EAN13") {
      setValue("978020137962"); // 12 digits (the 13th is the checksum generated by JsBarcode)
    } else if (format === "UPC") {
      setValue("12345678901"); // 11 digits
    } else if (format === "CODE128") {
      setValue("ZAVCLIP-123");
    } else {
      setValue("12345678");
    }
  }, [format]);

  // Download crisp SVG vector file
  const downloadSvg = () => {
    if (!svgRef.current || errorMsg) return;

    const serializer = new XMLSerializer();
    const source = serializer.serializeToString(svgRef.current);
    const svgBlob = new Blob([source], { type: "image/svg+xml;charset=utf-8" });
    const url = URL.createObjectURL(svgBlob);

    const link = document.createElement("a");
    link.href = url;
    link.download = `barcode-${value}-${Date.now()}.svg`;
    link.click();
    URL.revokeObjectURL(url);
  };

  // Render SVG to canvas and download high-quality PNG
  const downloadPng = () => {
    if (!svgRef.current || errorMsg) return;

    const svgElement = svgRef.current;
    const svgString = new XMLSerializer().serializeToString(svgElement);
    const svgBlob = new Blob([svgString], { type: "image/svg+xml;charset=utf-8" });
    const blobURL = URL.createObjectURL(svgBlob);

    const img = new Image();
    img.onload = () => {
      const canvas = document.createElement("canvas");
      const bbox = svgElement.getBoundingClientRect();
      
      // Let's set high resolution canvas drawing
      canvas.width = svgElement.clientWidth * 2 || 600;
      canvas.height = svgElement.clientHeight * 2 || 300;
      
      const ctx = canvas.getContext("2d");
      if (ctx) {
        ctx.fillStyle = bgColor;
        ctx.fillRect(0, 0, canvas.width, canvas.height);
        ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
        
        canvas.toBlob((blob) => {
          if (blob) {
            const pngURL = URL.createObjectURL(blob);
            const link = document.createElement("a");
            link.href = pngURL;
            link.download = `barcode-${value}-${Date.now()}.png`;
            link.click();
            URL.revokeObjectURL(pngURL);
          }
        }, "image/png");
      }
      URL.revokeObjectURL(blobURL);
    };
    img.src = blobURL;
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-950 dark:to-gray-900 py-12 px-4">
      <div className="container mx-auto max-w-4xl">
        {/* Navigation Breadcrumb */}
        <div className="mb-6 flex justify-between items-center">
          <Link
            href="/text"
            className="text-sm font-semibold text-emerald-600 dark:text-emerald-400 hover:underline flex items-center gap-1.5"
          >
            <span>➔</span> Quay lại bộ Tiện Ích
          </Link>
          <span className="text-xs bg-emerald-100 dark:bg-emerald-950/50 text-emerald-700 dark:text-emerald-400 px-3 py-1 rounded-full border border-emerald-500/20 font-medium">
            🔒 Bảo mật 100% - Dữ liệu không gửi lên máy chủ
          </span>
        </div>

        {/* Title */}
        <h1 className="text-3xl font-extrabold text-gray-900 dark:text-white mb-2 flex items-center gap-2">
          <span>🏷️</span> Trình Tạo Mã Vạch Barcode
        </h1>
        <p className="text-gray-500 dark:text-gray-400 text-sm mb-8">
          Tạo nhanh mã vạch (Barcode) theo nhiều chuẩn công nghiệp. Thích hợp cho kho bãi, hàng hóa, in ấn tem nhãn.
        </p>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          {/* Left Controls (col: 7) */}
          <div className="lg:col-span-7 bg-white dark:bg-gray-800 rounded-2xl border border-gray-100 dark:border-gray-750 shadow-md p-6 space-y-6">
            
            {/* Format choice */}
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-xs font-bold text-gray-400 uppercase mb-2">Định Dạng Mã Vạch</label>
                <select
                  value={format}
                  onChange={(e) => setFormat(e.target.value as BarcodeFormat)}
                  className="w-full bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-xl px-3 py-2.5 text-sm focus:outline-none focus:border-emerald-500 dark:text-white"
                >
                  <option value="CODE128">CODE128 (Đa năng, phổ biến)</option>
                  <option value="EAN13">EAN-13 (Hàng tiêu dùng, 12-13 số)</option>
                  <option value="UPC">UPC-A (Thị trường Mỹ, 11-12 số)</option>
                  <option value="CODE39">CODE-39 (Hỗ trợ chữ và số)</option>
                  <option value="ITF">ITF (Mã vạch vận tải)</option>
                </select>
              </div>

              <div>
                <label className="block text-xs font-bold text-gray-400 uppercase mb-2">Giá Trị Mã Vạch</label>
                <input
                  type="text"
                  value={value}
                  onChange={(e) => setValue(e.target.value)}
                  placeholder="Nhập chuỗi số/chữ..."
                  className="w-full bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:border-emerald-500 dark:text-white font-mono"
                />
              </div>
            </div>

            {/* Customization Sliders */}
            <div className="pt-4 border-t border-gray-100 dark:border-gray-750 space-y-4">
              <h3 className="text-sm font-bold text-gray-800 dark:text-gray-200">
                Tùy chỉnh kích thước & hiển thị
              </h3>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <div className="flex justify-between text-xs text-gray-500 mb-1">
                    <span>Chiều cao vạch</span>
                    <span className="font-mono">{height}px</span>
                  </div>
                  <input
                    type="range"
                    min="40"
                    max="180"
                    value={height}
                    onChange={(e) => setHeight(parseInt(e.target.value))}
                    className="w-full accent-emerald-500 h-2 bg-gray-200 dark:bg-gray-700 rounded-lg cursor-pointer"
                  />
                </div>

                <div>
                  <div className="flex justify-between text-xs text-gray-500 mb-1">
                    <span>Độ rộng nét vạch</span>
                    <span className="font-mono">{width}px</span>
                  </div>
                  <input
                    type="range"
                    min="1"
                    max="4"
                    value={width}
                    onChange={(e) => setWidth(parseInt(e.target.value))}
                    className="w-full accent-emerald-500 h-2 bg-gray-200 dark:bg-gray-700 rounded-lg cursor-pointer"
                  />
                </div>
              </div>

              {/* Display text toggle */}
              <div className="flex items-center justify-between py-2">
                <div>
                  <h4 className="text-xs font-semibold text-gray-700 dark:text-gray-300">Hiển thị chữ số ở dưới</h4>
                  <p className="text-[10px] text-gray-500">In kèm giá trị chuỗi văn bản dưới mã vạch</p>
                </div>
                <input
                  type="checkbox"
                  checked={displayValue}
                  onChange={(e) => setDisplayValue(e.target.checked)}
                  className="w-5 h-5 accent-emerald-500 cursor-pointer"
                />
              </div>
            </div>

            {/* Colors */}
            <div className="pt-4 border-t border-gray-100 dark:border-gray-750 grid grid-cols-2 gap-4">
              <div>
                <label className="block text-xs text-gray-500 mb-1">Màu Mã Vạch</label>
                <div className="flex items-center gap-2 bg-gray-50 dark:bg-gray-900 p-2 rounded-xl border border-gray-200 dark:border-gray-700">
                  <input
                    type="color"
                    value={lineColor}
                    onChange={(e) => setLineColor(e.target.value)}
                    className="w-8 h-8 rounded bg-transparent border-0 cursor-pointer"
                  />
                  <span className="text-xs font-mono text-gray-600 dark:text-gray-400">{lineColor}</span>
                </div>
              </div>

              <div>
                <label className="block text-xs text-gray-500 mb-1">Màu Nền</label>
                <div className="flex items-center gap-2 bg-gray-50 dark:bg-gray-900 p-2 rounded-xl border border-gray-200 dark:border-gray-700">
                  <input
                    type="color"
                    value={bgColor}
                    onChange={(e) => setBgColor(e.target.value)}
                    className="w-8 h-8 rounded bg-transparent border-0 cursor-pointer"
                  />
                  <span className="text-xs font-mono text-gray-600 dark:text-gray-400">{bgColor}</span>
                </div>
              </div>
            </div>

          </div>

          {/* Right Preview (col: 5) */}
          <div className="lg:col-span-5 flex flex-col items-center space-y-6">
            <div className="bg-white dark:bg-gray-800 rounded-2xl border border-gray-100 dark:border-gray-750 shadow-md p-6 w-full flex flex-col items-center">
              <h3 className="font-bold text-gray-800 dark:text-gray-200 text-sm mb-4 border-b border-gray-100 dark:border-gray-750 w-full pb-2 text-center">
                Mã vạch xem trước
              </h3>

              {errorMsg && (
                <div className="mb-4 p-3 bg-rose-50 dark:bg-rose-950/20 border border-rose-200 dark:border-rose-800/30 text-rose-600 dark:text-rose-400 rounded-xl text-center text-xs w-full">
                  ⚠️ {errorMsg}
                </div>
              )}

              {/* Barcode SVG Container */}
              <div className="bg-gray-50 dark:bg-gray-950 p-4 rounded-xl border border-gray-200 dark:border-gray-700 w-full min-h-[160px] flex items-center justify-center mb-6 shadow-inner overflow-x-auto">
                <svg ref={svgRef} className={`max-w-full ${errorMsg ? "opacity-30 pointer-events-none" : ""}`} />
              </div>

              {/* Actions */}
              <div className="w-full grid grid-cols-2 gap-3">
                <button
                  onClick={downloadPng}
                  disabled={!!errorMsg}
                  className="bg-emerald-600 hover:bg-emerald-700 text-white font-bold py-3 px-4 rounded-xl shadow-sm text-xs md:text-sm transition-all transform hover:-translate-y-0.5 active:translate-y-0 flex items-center justify-center gap-1.5 cursor-pointer disabled:opacity-50"
                >
                  📥 Tải PNG
                </button>
                <button
                  onClick={downloadSvg}
                  disabled={!!errorMsg}
                  className="bg-slate-700 hover:bg-slate-800 text-white font-bold py-3 px-4 rounded-xl shadow-sm text-xs md:text-sm transition-all transform hover:-translate-y-0.5 active:translate-y-0 flex items-center justify-center gap-1.5 cursor-pointer disabled:opacity-50"
                >
                  🎨 Tải Vector SVG
                </button>
              </div>
            </div>

            <div className="bg-gradient-to-br from-indigo-50 to-blue-50 dark:from-indigo-950/20 dark:to-blue-950/20 border border-indigo-500/20 rounded-2xl p-5 text-xs text-indigo-800 dark:text-indigo-400 leading-relaxed shadow-sm w-full">
              <h4 className="font-bold mb-1.5 flex items-center gap-1">
                <span>📌</span> Lưu ý về định dạng:
              </h4>
              <ul className="list-disc pl-4 space-y-1">
                <li><strong>EAN-13:</strong> Thích hợp cho sản phẩm bán lẻ quốc tế. Cần đúng 12 chữ số (số thứ 13 là tổng kiểm tra tự động).</li>
                <li><strong>CODE128:</strong> Định dạng đa năng nhất, hỗ trợ cả chữ cái, chữ số và các ký tự đặc biệt. Không giới hạn độ dài nét vẽ.</li>
              </ul>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
}
